version: "2"
run:
  timeout: 5m

linters:
  default: "standard"
  enable:
    - govet # Обязательный: проверяет корректность кода
    - staticcheck # Обязательный: глубокий анализ, находит ошибки
    - errcheck # Критично: проверяет, что ошибки не игнорируются
    - gosec # Важно: сканирование на проблемы безопасности
    - revive # Гибкая проверка стиля (альтернатива устаревшему golint)
    - gocyclo # Проверка цикломатической сложности функций
    - unconvert # Находит лишние преобразования типов
    - misspell # Проверяет орфографию в комментариях
linters-settings:
  gocyclo:
    min-complexity: 15 # Порог сложности, при котором линтер будет ругаться
  revive:
    severity: warning
