services:
  knowledge:
    build:
      context: .
      dockerfile: services/knowledge/Dockerfile
    container_name: knowledge
    ports:
      - "50051:50051"
    environment:
      # - GRPC_HOST=0.0.0.0
      - GRPC_PORT=50051
      # - LOG_LEVEL=DEBUG
      - NEO4J_URI=neo4j://neo4j:7687
    env_file:
      - services/knowledge/.env
    depends_on:
      - neo4j
    restart: unless-stopped

  neo4j:
    build:
      context: .
      dockerfile: build/Dockerfile.neo4j
    container_name: neo4j
    ports:
      - "7474:7474" # web interface
      - "7687:7687" # bolt (connect to db)
    environment:
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_unmanaged__extension__classes=n10s.endpoint=/rdf
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,n10s.*
    volumes:
      - neo4j:/data
    secrets:
      - neo4j_auth_file
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]      
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
  
  neo4j_init:
    build:
      context: .
      dockerfile: build/Dockerfile.neo4j    
    container_name: neo4j_init
    depends_on:
      neo4j:
        condition: service_healthy
    secrets:
      - neo4j_auth_file
    command: > 
      sh -c "
        echo 'Starting preparing n10s...'

        AUTH_STR=$$(cat /run/secrets/neo4j_auth_file)
        USER=$$(echo $$AUTH_STR | cut -d'/' -f1)
        PASS=$$(echo $$AUTH_STR | cut -d'/' -f2)

        cypher-shell -a neo4j://neo4j:7687 -u $$USER -p $$PASS 'CREATE CONSTRAINT n10s_unique_uri IF NOT EXISTS FOR (r:Resource) REQUIRE r.uri IS UNIQUE;'
        
        CONFIG_EXISTS=$$(cypher-shell -a neo4j://neo4j:7687 -u $$USER -p $$PASS 'CALL n10s.graphconfig.show()' | grep -c 'handleVocabUris' || true)
        
        if [ $$CONFIG_EXISTS -eq 0 ]; then
          echo 'Graph is empty, running n10s.graphconfig.init()...'
          cypher-shell -a neo4j://neo4j:7687 -u $$USER -p $$PASS 'CALL n10s.graphconfig.init({handleVocabUris: \"MAP\", applyNeo4jNaming: true});'
        else
          echo 'n10s is already prepared, skipping.'
        fi
        
        echo 'n10s preparing finished'
      "


volumes:
  neo4j:

secrets:
  neo4j_auth_file:
    file: ./secrets/neo4j_auth.txt