services:
  knowledge:
    image: erudition-app-knowledge:latest
    build:
      context: .
      dockerfile: services/knowledge/Dockerfile
    ports:
      - "50051:50051"
    environment:
      # - GRPC_HOST=0.0.0.0
      - GRPC_PORT=50051
      # - LOG_LEVEL=DEBUG
      - NEO4J_URI=neo4j://neo4j:7687
    env_file:
      - services/knowledge/.env
    depends_on:
      - neo4j
    restart: unless-stopped

  neo4j:
    image: erudition-app-neo4j:latest
    build:
      context: .
      dockerfile: build/Dockerfile.neo4j
    ports:
      - "7474:7474" # web interface
      - "7687:7687" # bolt (connect to db)
    environment:
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_unmanaged__extension__classes=n10s.endpoint=/rdf
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,n10s.*
    volumes:
      - neo4j:/data
    secrets:
      - neo4j_auth_file
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]      
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
  
  neo4j_init:
    image: erudition-app-neo4j_init:latest
    build:
      context: .
      dockerfile: build/Dockerfile.neo4j    
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
    secrets:
      - neo4j_auth_file
    command: /usr/local/bin/init-n10s.sh


volumes:
  neo4j:

secrets:
  neo4j_auth_file:
    file: ./secrets/neo4j_auth.txt